### ISSUE TITLE
Task with name 'jar' not found in root project 'pipeline'.  

### ISSUE THREAD

**Issue by unoexperto** [kordamp/yguard-gradle-plugin#1]
Thank you for your plugin, @aalmiray.

Unfortunately I can't use it in multiplatform project. I get following exception. What would you suggest to do ?

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'jar' not found in root project 'pipeline'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:360)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:112)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:375)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:122)
        at org.kordamp.gradle.plugin.yguard.YGuardPlugin$1.execute(YGuardPlugin.groovy:54)
        at org.kordamp.gradle.plugin.yguard.YGuardPlugin$1.execute(YGuardPlugin.groovy)

```

Also, could you advice how to invoke `yguard.jar` manually in command line ? I couldn't find documentation on its command-line parameters.

**Comment by aalmiray** [comment]
> Unfortunately I can't use it in multiplatform project. 

What do you mean by this? The yguard plugin must be applied to a project that also has the `java-base` plugin applied to it.

> Also, could you advice how to invoke yguard.jar manually in command line ? I couldn't find documentation on its command-line parameters.

The default `yguardMain` task and the task type `org.kordamp.gradle.plugin.yguard.tasks.YGuardGradleTask` do not expose options configurable via command line arguments. Every option must be configured using the DSL as explained in the guide https://kordamp.org/yguard-gradle-plugin/

**Comment by rzabini** [comment]
Hi,
I got the same error. In [Gradle docs](https://docs.gradle.org/current/userguide/designing_gradle_plugins.html) I see:

> The Java Base plugin [...] doesn’t actually create tasks you’d use as a Java developer on a regular basis
> The Java plugin [...] creates tasks well-known to Java developers like classes, jar 

So I guess that the `jar` task is not guaranteed to be present when the `java-base` plugin has been applied, hence the _Task with name 'jar' not found_ error. Maybe this:

`project.pluginManager.withPlugin('java-base', new Action<AppliedPlugin>() {`

should instead be:

`project.pluginManager.withPlugin('java', new Action<AppliedPlugin>() {'` ?

**Comment by aalmiray** [comment]
Indeed. Using `java` would still work for Java, Groovy, Scala, and Kotlin projects as their language plugins apply the `java` plugin, don't they? However this will make android projects fail if not mistaken. I suppose that as long as the `java` or `java-library` plugins are applied to the project then this plugin will work alright.

Question is, what to do when that is not the case, as the expectation is to obfuscate a JAR. It does not have to be the one provided by the default `jar` task.
